#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "comparador-de-indicadores-municipais"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "guisposi"

[assets]
directory = "./view-build"
binding = "ASSETS"

[deco]
workspace = "guisposi"
enable_workflows = true
local = false

[[deco.bindings]]
name = "MCP_GMAIL_N1"
type = "mcp"
integration_id = "i:0ef30aab-f9e4-4185-9490-05a0653a5709"

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"

[[rules]]
type = "Text"
globs = [ "**/*.sql" ]
fallthrough = true